---
title: "Activity title"
format: 
  html:
    toc: false
    css: css/styles.css
    echo: false
    mainfont: Helvetica, sans-serif
    embed-resources: true
---

```{r LoadSettings}
#| include: false
knitr::opts_chunk$set(dev.args=list(bg="transparent"))
knitr::opts_chunk$set(dev.args = list(png = list(type = "cairo")))

# Load libraries
library(tidyverse)
library(grid)

# Load functions for docs
purrr::map(list.files(path = "./utils/", pattern = ".R$", recursive = TRUE, full.names = TRUE),
           source) %>%
  invisible()
```


``` {r SkillsRequiredBox}
#| output: asis
#| eval: true

# Output a box detailing the skills required for this challenge
## If you wish this to be a mystery, set eval to false
fSkillsRequired(c("Problem solving", "Algorithms"))
```

``` {r DifficultyRating}
#| eval: true
#| fig-height: 0.7
#| fig-width: 4
#| fig-align: center

# Output a rating estimate to help the participants triage the activities
fDifficultyEstimate(1) %>%
  grid::grid.draw()
```

Explanatory text and instructions for the activity here. Print page for output, or Print and Save to PDF. HTML output was chosen as it is platform- and environment-agnostic while PDF output requires a LaTeX installation.
